# Generated by Django 3.2.7 on 2022-01-29 00:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gltf', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/city3d/buildings/austin/gltf'), upload_to='')),
                ('img', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/city3d/buildings/austin/img'), upload_to='')),
                ('img_cred', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10)),
                ('model_rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('viewport_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8)),
                ('viewport_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('link', models.URLField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('permittype', models.CharField(max_length=20)),
                ('permit_number', models.CharField(max_length=20)),
                ('permit_class_mapped', models.CharField(max_length=20)),
                ('issue_date', models.DateTimeField()),
                ('issued_in_last_30_days', models.CharField(max_length=3)),
                ('status_current', models.CharField(max_length=20)),
                ('expiresdate', models.DateTimeField()),
                ('original_address1', models.CharField(max_length=64)),
                ('original_city', models.CharField(max_length=64)),
                ('original_state', models.CharField(max_length=64)),
                ('original_zip', models.IntegerField()),
                ('link', models.URLField()),
                ('project_id', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10)),
                ('total_job_valuation', models.FloatField()),
            ],
            options={
                'db_table': 'city3d_permit',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('initials', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'city3d_state',
            },
        ),
    ]
