# Generated by Django 3.2.7 on 2022-02-07 04:14

import city3d.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img', models.FileField(storage=city3d.models.MyStorage(), upload_to='')),
                ('img_cred', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('developer', models.CharField(blank=True, default='', max_length=64)),
                ('contractor', models.CharField(blank=True, default='', max_length=64)),
                ('architect', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('viewport_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8)),
                ('viewport_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(max_length=20)),
                ('permit_number', models.CharField(max_length=20)),
                ('permit_class', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('last_30_days', models.CharField(max_length=3)),
                ('current_status', models.CharField(max_length=20)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip', models.IntegerField()),
                ('link', models.URLField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20)),
                ('valuation', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='city3d.building')),
            ],
            options={
                'db_table': 'permits',
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('link', models.URLField()),
                ('img', models.URLField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headlines', to='city3d.building')),
            ],
            options={
                'db_table': 'headlines',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='city3d.city'),
        ),
        migrations.AddField(
            model_name='building',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='city3d.permit'),
        ),
    ]
