# Generated by Django 3.2.7 on 2022-02-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='city3d.building'),
        ),
        migrations.AlterField(
            model_name='building',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='city3d.permit'),
        ),
    ]
