# Generated by Django 3.2.7 on 2022-02-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='building',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='building',
            name='model_rotation',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='building',
        ),
    ]
