# Generated by Django 3.2.7 on 2022-01-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='buildings',
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='headline',
            table='headlines',
        ),
    ]
