# Generated by Django 3.2.7 on 2021-12-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0002_auto_20211226_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
