# Generated by Django 3.2.7 on 2022-02-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0002_auto_20220205_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='city3d.building'),
        ),
    ]
