# Generated by Django 3.2.7 on 2022-02-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0002_auto_20220203_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20),
        ),
    ]
