# Generated by Django 3.2.7 on 2022-01-11 01:23

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0003_city_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/gltf/buildings'), upload_to='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('drawing_url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='city3d.city')),
            ],
        ),
    ]
