# Generated by Django 3.2.7 on 2022-02-07 02:14

import city3d.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0004_alter_building_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.FileField(storage=city3d.models.MyStorage(), upload_to=''),
        ),
    ]
