# Generated by Django 3.2.7 on 2022-02-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0004_auto_20220204_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='city3d.building'),
        ),
    ]
