# Generated by Django 3.2.7 on 2022-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0005_headline_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
