# Generated by Django 3.2.7 on 2022-02-04 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0006_alter_permit_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headlines', to='city3d.building'),
        ),
    ]
