# Generated by Django 3.2.7 on 2022-02-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0007_alter_headline_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='city3d.city'),
        ),
    ]
