# Generated by Django 3.2.7 on 2022-02-04 22:06

import city3d.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0008_building_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='gltf',
            field=models.FileField(storage=city3d.models.MyStorage(django.core.files.storage.FileSystemStorage(location='/static/city3d/buildings/austin/gltf')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.FileField(storage=city3d.models.MyStorage(django.core.files.storage.FileSystemStorage(location='/static/city3d/buildings/austin/img')), upload_to=''),
        ),
    ]
