# Generated by Django 3.2.7 on 2022-02-04 22:06

import city3d.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city3d', '0009_auto_20220204_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='gltf',
            field=models.FileField(storage=city3d.models.MyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.FileField(storage=city3d.models.MyStorage(), upload_to=''),
        ),
    ]
